style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/Mrgi23/programmable-signal-generator
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - test
        - ci
        - docs
        - chore
        - style
        - revert
  commit_groups:
    group_by: Type
    sort_by: Custom
    title_order:
      - feat
      - fix
      - perf
      - refactor
      - test
      - ci
      - docs
      - chore
      - style
      - revert
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      test: Tests
      ci: CI/CD Pipelines
      docs: Documentation
      chore: Maintenance
      style: Formatting
      revert: Reverts
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
      